env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  react/prop-types: off
  react/jsx-filename-extension: off
ignorePatterns:
  - src/reportWebVitals.js
  - src/index.js
