version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=protein_matcher_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  migration:
    build: .
    command: ["python", "manage.py", "migrate"]
    environment:
      - DJANGO_DEVELOPMENT=true
    volumes:
      - .:/code
    depends_on:
      - db
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      - DJANGO_DEVELOPMENT=true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration
  frontend:
    build: ./frontend
    command: ["yarn", "start"]
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"

