version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=protein_matcher_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    image: 7imon7ays/protein-matcher_web:latest
    command: [sh, -c, "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    environment:
      - DJANGO_DEVELOPMENT=true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
  background_worker:
    image: 7imon7ays/protein-matcher_background_worker:latest
    command: ["python", "manage.py", "process_tasks"]
    environment:
      - DJANGO_DEVELOPMENT=true
    volumes:
      - .:/code
    restart: always
    depends_on:
      - web
  frontend:
    image: 7imon7ays/protein-matcher_frontend:latest
    command: ["yarn", "start"]
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - web

volumes:
  pgdata:
