# Generated by Django 3.2.4 on 2021-06-17 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_string', models.CharField(max_length=20)),
                ('dna_sequence', models.TextField()),
                ('protein_id', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('WAIT', 'Waiting'), ('RUN', 'Running'), ('PAUSE', 'Pausing'), ('DONE', 'Done')], default='WAIT', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
