export const DNA_SEQUENCES_EXAMPLES = {
  CAAACGAGGTCTTCGGTTGTATATGTTCTCTGGCAATCACTAAGGGCCGCCCGGTGTCATCTGCCGCATC: 'NC_000852',
  AATGTTTTATTTGGAATCTTTTTGCATATATGACATTTACCGTCAACTGGAAATGGAGTATTCCTCTTTA: 'NC_007346',
  TTTTCCATGTGTATTTTGAAAGATCCCCTCCAGCAAATTCTGGGCGACCCCACCAAAAGAATTTGTTAAT: 'NC_008724',
  ATAGTATATGGTCTTGTATCGACAAATTTCTGTTTGATGGTATACGGTAAATCACTAAGGTCGCCTCGGT: 'NC_009899',
  AACTTTTGGGTAAAACATTTTCTTCTATTTTTTGATTATAACAATATCCAAATGTTAAATATGTTAAACT: 'NC_014637',
};

export const NCBI_PATH = 'https://www.ncbi.nlm.nih.gov/nuccore/';

export const FOUND = 'FOUND';
export const NOT_FOUND = 'EMPTY';
